declare module '*.ico';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.eot';
declare module '*.wof';
declare module '*.woff';
declare module '*.woff2';
